<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="asd1558po01976" name="Default test" tests="11" failures="1" timestamp="29 Jun 2018 06:02:45 GMT" time="39.48" errors="0">
  <testcase name="advancedCourse" time="1.454" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="hoverMenu" time="0.088" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="proceedWithoutEnteringCredentials" time="1.075" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="queryGate" time="3.23" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="clickOnProceedWithoutPostHttpRequest" time="0.067" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="restApiGenerateToken" time="0.074" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="restApiPostMethod" time="0.028" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="DownlaodFileandEnterSignatue" time="1.131" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="ProceedAfter30Seconds" time="32.084" classname="com.qait.snl.advancedTatoc.TestAdvanced">
    <failure type="java.lang.AssertionError" message="expected [http://10.0.1.86/tatoc/advanced/file/handle] but found [http://10.0.1.86/tatoc/error]">
      <![CDATA[java.lang.AssertionError: expected [http://10.0.1.86/tatoc/advanced/file/handle] but found [http://10.0.1.86/tatoc/error]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.qait.snl.advancedTatoc.Assertion.putAssertionNewtoCheckErrorPage(Assertion.java:23)
	at com.qait.snl.advancedTatoc.TestAdvanced.ProceedAfter30Seconds(TestAdvanced.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ProceedAfter30Seconds -->
  <testcase name="ProceedWithoutDownloadingFile" time="0.103" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
  <testcase name="ProceedWithoutEnteringSignature" time="0.107" classname="com.qait.snl.advancedTatoc.TestAdvanced"/>
</testsuite> <!-- Default test -->
